# Maps predicted disease to triage priority (low / moderate / high / emergency)
# Medical judgment: emergency = life-threatening without immediate care,
# high = needs doctor same day, moderate = needs doctor within a day or two, low = self-care first

DISEASE_PRIORITY = {
    "Heart attack":                             "emergency",
    "Paralysis (brain hemorrhage)":             "emergency",
    "Pneumonia":                                "emergency",
    "Tuberculosis":                             "high",
    "Dengue":                                   "high",
    "Malaria":                                  "high",
    "Typhoid":                                  "high",
    "Hepatitis B":                              "high",
    "Hepatitis C":                              "high",
    "Hepatitis D":                              "high",
    "Hepatitis E":                              "high",
    "hepatitis A":                              "high",
    "Alcoholic hepatitis":                      "high",
    "Chronic cholestasis":                      "high",
    "Jaundice":                                 "high",
    "AIDS":                                     "high",
    "Hypoglycemia":                             "high",
    "Hypertension":                             "high",
    "Diabetes":                                 "high",
    "Bronchial Asthma":                         "high",
    "Migraine":                                 "moderate",
    "GERD":                                     "moderate",
    "Peptic ulcer diseae":                      "moderate",
    "Gastroenteritis":                          "moderate",
    "Drug Reaction":                            "moderate",
    "(vertigo) Paroymsal  Positional Vertigo":  "moderate",
    "Hypothyroidism":                           "moderate",
    "Hyperthyroidism":                          "moderate",
    "Cervical spondylosis":                     "moderate",
    "Osteoarthristis":                          "moderate",
    "Varicose veins":                           "moderate",
    "Common Cold":                              "low",
    "Chicken pox":                              "low",
    "Allergy":                                  "low",
    "Fungal infection":                         "low",
    "Impetigo":                                 "low",
    "Acne":                                     "low",
    "Psoriasis":                                "low",
}

PRIORITY_LABELS = {
    "low":       "✅ Low Priority",
    "moderate":  "⚠ Moderate Priority",
    "high":      "🔴 High Priority",
    "emergency": "🚨 Emergency — Seek Immediate Care",
}
